# Generated by Django 4.2.7 on 2023-11-28 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
