# Generated by Django 4.2.7 on 2023-12-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_categoria_cliente_metododecobro_metododepago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='idSer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='idServicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
