# Generated by Django 4.2.7 on 2023-12-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_servicio_idser_alter_servicio_idservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='idServicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='idSer',
        ),
        migrations.AddField(
            model_name='servicio',
            name='idCategoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prueba.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCat',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='idServicio',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
