# Generated by Django 4.2.7 on 2023-12-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0005_remove_categoria_idservicio_remove_servicio_idser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='default_value', max_length=70),
        ),
    ]
