# Generated by Django 4.2.7 on 2023-12-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0007_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='desc',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
