# Generated by Django 4.2.7 on 2023-12-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0008_producto_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='desc',
            field=models.IntegerField(default=0),
        ),
    ]
