# Generated by Django 4.2.7 on 2023-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0009_alter_producto_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='clase_css',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
