# Generated by Django 4.2.7 on 2023-12-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0013_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.IntegerField()),
                ('categoria', models.IntegerField(choices=[[900, 'Diseño Web'], [901, 'Front End'], [902, 'Back End'], [903, 'Logo & Marca'], [904, 'Diseño de Apps'], [905, 'Arte'], [906, 'Ilustr,aciones'], [907, 'Diseño UX'], [908, 'Gaming'], [909, 'Diseño 3D'], [910, 'Marketing Digital'], [911, 'Soporte'], [912, 'Programacion y Tecnologia'], [913, 'Datos'], [914, 'Fotografia y Edicion'], [915, 'Videos y Edición']])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
    ]
