# Generated by Django 4.2.7 on 2023-12-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0014_serviciob'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciob',
            name='nombreSer',
            field=models.CharField(default='¿Qué servicio brindas?', max_length=70, null=True),
        ),
    ]
