# Generated by Django 4.2.7 on 2023-12-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0015_serviciob_nombreser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciob',
            old_name='nombreSer',
            new_name='servicio',
        ),
    ]
