# Generated by Django 4.2.7 on 2023-12-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0016_rename_nombreser_serviciob_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciob',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='serviciob',
            name='servicio',
            field=models.CharField(max_length=80),
        ),
    ]
