# Generated by Django 4.2.7 on 2023-12-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0017_remove_serviciob_nombre_alter_serviciob_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciob',
            name='servicio',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
