# Generated by Django 4.2.7 on 2023-12-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0021_alter_serviciob_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='metododepago',
            name='idServicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prueba.servicio'),
        ),
    ]
