# Generated by Django 4.2.7 on 2023-12-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0023_alter_metododecobro_idmetod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metododecobro',
            name='tipoMet',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='metododepago',
            name='idPago',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metododepago',
            name='tipoMetPag',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
